# Generated by Django 6.1.1 on 2026-09-25 15:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=30, validators=[django.core.validators.MinLengthValidator(7)])),
                ('provincia', models.CharField(blank=True, max_length=100)),
                ('campo_estudio', models.CharField(blank=True, max_length=150)),
                ('colectivo', models.CharField(blank=True, max_length=100)),
                ('consentimiento_rgpd', models.BooleanField(default=False)),
                ('sesion_uuid', models.UUIDField(blank=True, db_index=True, null=True)),
                ('procesado', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-creado_en'],
                'constraints': [models.CheckConstraint(condition=models.Q(('email__gt', ''), ('telefono__gt', ''), _connector='OR'), name='lead_email_or_phone'), models.CheckConstraint(condition=models.Q(('email', ''), models.Q(('email__contains', ' '), _negated=True), _connector='OR'), name='lead_email_no_spaces')],
            },
        ),
    ]
