# Generated by Django 6.1.1 on 2026-09-28 13:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='lead',
            name='lead_email_or_phone',
        ),
        migrations.RemoveConstraint(
            model_name='lead',
            name='lead_email_no_spaces',
        ),
        migrations.AlterField(
            model_name='lead',
            name='campo_estudio',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='lead',
            name='colectivo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='lead',
            name='provincia',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lead',
            name='sesion_uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='telefono',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.CheckConstraint(condition=models.Q(('email__isnull', False), ('telefono__isnull', False), _connector='OR'), name='lead_email_o_telefono'),
        ),
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.CheckConstraint(condition=models.Q(('consentimiento_rgpd', True)), name='lead_consentimiento_rgpd'),
        ),
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.CheckConstraint(condition=models.Q(('nombre__isnull', False), models.Q(('nombre', ''), _negated=True)), name='lead_nombre_no_vacio'),
        ),
        migrations.RemoveField(
            model_name='lead',
            name='actualizado_en',
        ),
    ]
