# Generated by Django 6.1.1 on 2026-10-02 13:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_remove_lead_lead_email_or_phone_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='lead',
            name='lead_email_o_telefono',
        ),
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='lead',
            name='sesion_uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.CheckConstraint(condition=models.Q(('email__gt', ''), ('telefono__gt', ''), _connector='OR'), name='lead_email_o_telefono'),
        ),
    ]
