# Generated by Django 6.1.1 on 2026-09-30 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_remove_lead_lead_email_or_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='experiencia_profesional',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='objetivo',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
