# Generated by Django 6.1.1 on 2026-10-02 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_lead_experiencia_profesional_lead_objetivo'),
        ('leads', '0004_fix_lead_contacto_constraint'),
    ]

    operations = [
    ]
