# Generated by Django 6.1.1 on 2026-10-02 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_merge_20261002_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='experiencia_profesional',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='objetivo',
        ),
    ]
