# Generated by Django 6.1.1 on 2026-09-23 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StagingCursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_raw', models.TextField()),
                ('contenido_raw', models.TextField(blank=True, null=True)),
                ('provincia_raw', models.TextField(blank=True, null=True)),
                ('campo_estudio_raw', models.TextField(blank=True, null=True)),
                ('colectivo_raw', models.TextField(blank=True, null=True)),
                ('url_origen', models.TextField(blank=True, null=True)),
                ('hash_contenido', models.CharField(max_length=64, unique=True)),
                ('estado', models.CharField(default='pendiente', max_length=20)),
                ('extraido_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'staging_cursos',
            },
        ),
        migrations.CreateModel(
            name='BaseConocimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('contenido', models.TextField()),
                ('provincia', models.CharField(max_length=100)),
                ('campo_estudio', models.CharField(max_length=100)),
                ('colectivo', models.CharField(max_length=100)),
                ('url_oficial', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('vector_busqueda', models.TextField(editable=False, null=True, blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'base_conocimiento',
                'indexes': [models.Index(fields=['provincia'], name='idx_bc_provincia'), models.Index(fields=['campo_estudio'], name='idx_bc_campo'), models.Index(fields=['colectivo'], name='idx_bc_colectivo')],
            },
        ),
    ]
