# Generated by Django 6.1.1 on 2026-09-24 14:16

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conocimiento', '0002_auto_20260923_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseconocimiento',
            name='vector_busqueda',
            field=django.contrib.postgres.search.SearchVectorField(editable=False),
        ),
        migrations.AddIndex(
            model_name='baseconocimiento',
            index=django.contrib.postgres.indexes.GinIndex(fields=['vector_busqueda'], name='idx_bc_fts_gin'),
        ),
        migrations.AddIndex(
            model_name='stagingcursos',
            index=models.Index(fields=['estado'], name='idx_staging_estado'),
        ),
    ]
