# Generated by Django 6.1.1 on 2026-09-30 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conocimiento', '0002_trigger_vector_busqueda'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseconocimiento',
            name='localidad',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='stagingcursos',
            name='localidad',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='baseconocimiento',
            index=models.Index(fields=['localidad'], name='idx_bc_localidad'),
        ),
    ]
