# Generated by Django 6.1.1 on 2026-10-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conocimiento', '0004_url_oficial_unique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stagingcursos',
            name='url_origen',
        ),
        migrations.AddField(
            model_name='stagingcursos',
            name='url_oficial',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='baseconocimiento',
            name='url_oficial',
            field=models.TextField(blank=True, null=True),
        ),
    ]
