# Generated by Django 6.1.1 on 2026-10-02 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conocimiento', '0005_remove_stagingcursos_url_origen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagingcursos',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('validado', 'Validado'), ('procesado', 'Procesado'), ('error', 'Error')], default='pendiente', max_length=20),
        ),
    ]
