# Generated by Django 6.1.1 on 2026-10-02 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conocimiento', '0006_alter_stagingcursos_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseconocimiento',
            name='colectivo',
            field=models.CharField(choices=[('Desempleados', 'Desempleados'), ('Ocupados', 'Trabajadores Ocupados'), ('Autónomos', 'Autónomos'), ('Jóvenes', 'Garantía Juvenil'), ('General', 'Público General')], default='General', max_length=100),
        ),
        migrations.AlterField(
            model_name='baseconocimiento',
            name='provincia',
            field=models.CharField(choices=[('Ávila', 'Ávila'), ('Burgos', 'Burgos'), ('León', 'León'), ('Palencia', 'Palencia'), ('Salamanca', 'Salamanca'), ('Segovia', 'Segovia'), ('Soria', 'Soria'), ('Valladolid', 'Valladolid'), ('Zamora', 'Zamora'), ('General', 'General/Nacional'), ('N/D', 'No Definido')], default='N/D', max_length=100),
        ),
    ]
