# Generated by Django 6.1.1 on 2026-09-28 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesiones', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='mensaje',
            constraint=models.CheckConstraint(condition=models.Q(('rol__in', ['user', 'bot'])), name='mensaje_rol_valido'),
        ),
    ]
