# Generated by Django 6.1.1 on 2026-09-23 17:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provincia', models.CharField(blank=True, max_length=100, null=True)),
                ('campo_estudio', models.CharField(blank=True, max_length=100, null=True)),
                ('colectivo', models.CharField(blank=True, max_length=100, null=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('ultima_actividad', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sesion',
                'indexes': [models.Index(fields=['ultima_actividad'], name='idx_sesion_actividad')],
            },
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=10)),
                ('contenido', models.TextField()),
                ('fallback_activado', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('sesion', models.ForeignKey(db_column='sesion_uuid', on_delete=django.db.models.deletion.CASCADE, to='chat.sesion')),
            ],
            options={
                'db_table': 'mensaje',
                'indexes': [models.Index(fields=['sesion'], name='idx_mensaje_sesion')],
                'constraints': [models.CheckConstraint(condition=models.Q(('rol__in', ['user', 'bot'])), name='chk_mensaje_rol')],
            },
        ),
    ]
