# Generated by Django 6.1.1 on 2026-09-24 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mensaje',
            options={'ordering': ['creado_en']},
        ),
        migrations.RemoveIndex(
            model_name='mensaje',
            name='idx_mensaje_sesion',
        ),
        migrations.AddIndex(
            model_name='mensaje',
            index=models.Index(fields=['sesion', 'creado_en'], name='idx_mensaje_sesion_fecha'),
        ),
    ]
