# Generated by Django 6.1.1 on 2026-09-23 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultaFallida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_consulta', models.TextField()),
                ('provincia', models.CharField(blank=True, max_length=100, null=True)),
                ('campo_estudio', models.CharField(blank=True, max_length=100, null=True)),
                ('colectivo', models.CharField(blank=True, max_length=100, null=True)),
                ('motivo_fallo', models.CharField(max_length=30)),
                ('procesado', models.BooleanField(default=False)),
                ('registrado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'consulta_fallida',
            },
        ),
        migrations.CreateModel(
            name='ContadorDemanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_conocimiento_id', models.BigIntegerField()),
                ('provincia', models.CharField(max_length=100)),
                ('campo_estudio', models.CharField(max_length=100)),
                ('colectivo', models.CharField(max_length=100)),
                ('total_consultas', models.IntegerField(default=1)),
                ('ultima_consulta', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'contador_demanda',
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('provincia', models.CharField(max_length=100)),
                ('campo_estudio', models.CharField(max_length=100)),
                ('colectivo', models.CharField(max_length=100)),
                ('consentimiento_rgpd', models.BooleanField()),
                ('sesion_uuid', models.UUIDField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('procesado', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'lead',
                'constraints': [models.CheckConstraint(condition=models.Q(('email__isnull', False), ('telefono__isnull', False), _connector='OR'), name='chk_lead_contacto'), models.CheckConstraint(condition=models.Q(('consentimiento_rgpd', True)), name='chk_lead_rgpd'), models.CheckConstraint(condition=models.Q(('provincia__isnull', False), ('campo_estudio__isnull', False), ('colectivo__isnull', False)), name='chk_lead_contexto')],
            },
        ),
    ]
