# Generated by Django 6.1.1 on 2026-09-24 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='consultafallida',
            index=models.Index(fields=['procesado'], name='idx_cf_procesado'),
        ),
        migrations.AddIndex(
            model_name='contadordemanda',
            index=models.Index(fields=['base_conocimiento_id'], name='idx_contador_bc'),
        ),
        migrations.AddConstraint(
            model_name='contadordemanda',
            constraint=models.UniqueConstraint(fields=('base_conocimiento_id', 'provincia', 'campo_estudio', 'colectivo'), name='uq_contador_demanda'),
        ),
    ]
