# Generated by Django 6.1.1 on 2026-09-28 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0003_provincia_localidad'),
        ('operaciones', '0004_poblar_provincias_cyl'),
    ]

    operations = [
    ]
