# Generated by Django 6.1.1 on 2026-09-28 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0006_poblar_localidades_cyl'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='localidad',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
