# Generated by Django 6.1.1 on 2026-09-28 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultaFallida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo_fallo', models.TextField()),
                ('procesado', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Consulta fallida',
                'verbose_name_plural': 'Consultas fallidas',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='ContadorDemanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_conocimiento_id', models.IntegerField()),
                ('demanda', models.PositiveIntegerField(default=0)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contador de demanda',
                'verbose_name_plural': 'Contadores de demanda',
                'ordering': ['-demanda'],
                'indexes': [models.Index(fields=['-demanda'], name='telemetry_demanda_idx')],
            },
        ),
    ]
