# Generated by Django 6.1.1 on 2026-09-28 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contadordemanda',
            name='base_conocimiento_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AddIndex(
            model_name='contadordemanda',
            index=models.Index(fields=['base_conocimiento_id'], name='telemetry_bc_id_idx'),
        ),
    ]
