# Generated by Django 6.1.1 on 2026-10-01 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0002_alter_contadordemanda_base_conocimiento_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultafallida',
            name='texto_consulta',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='consultafallida',
            name='motivo_fallo',
            field=models.CharField(max_length=50),
        ),
    ]
